apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-red
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: node-red
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/node-red
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: cluster.top_level_domain
          value: {{ .Values.cluster.top_level_domain }}
        - name: cluster.name
          value: {{ .Values.cluster.name }}
        - name: cluster.admin_email
          value: {{ .Values.cluster.admin_email }}
        - name: cluster.timezone
          value: {{ .Values.cluster.timezone }}
          
        - name: app-template.persistence.config.enabled
          value: "true"
        
        - name: application.group
          value: Home Automation

        # renovate custom-docker versioning=semver
        - name: app-template.controllers.main.containers.main.image.repository
          value: docker.io/nodered/node-red
        - name: app-template.controllers.main.containers.main.image.tag
          value: 4.1.0

  syncPolicy:
{{ if .Values.spec.syncPolicy.automated.enabled }}
    automated: {}
{{ end }}
    syncOptions:
      - CreateNamespace=true
