apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Application
metadata:
  name: nas
  namespace: hajimari
spec:
  name: Synology
  group: Infrastructure
  icon: nas
  url: http://nas.{{ .Values.cluster.top_level_domain }}
  info: Storage
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Application
metadata:
  name: old-homeassistant
  namespace: hajimari
spec:
  name: old Home Assistant
  group: Utilities
  icon: home-assistant
  url: http://homeassistant.{{ .Values.cluster.top_level_domain }}:8123
  info: Home automation
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Application
metadata:
  name: valetudo
  namespace: hajimari
spec:
  name: Vacuum
  group: Home Automation
  icon: robot-vacuum
  url: http://valetudo.{{ .Values.cluster.top_level_domain }}
  info: Home automation
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: hajimari
spec:
  name: UniFi
  group: Infrastructure
  icon: arcticons:unifi-network
  url: http://unifi.{{ .Values.cluster.top_level_domain }}:8443
  info: Manage WIFI 
# ---
# apiVersion: startpunkt.ullberg.us/v1alpha1
# kind: Application
# metadata:
#   name: firewall
#   namespace: hajimari
# spec:
#   name: Router
#   group: Infrastructure
#   icon: router-network
#   url: http://firewall.{{ .Values.cluster.top_level_domain }}
#   info: Manage firewall
# ---
# apiVersion: startpunkt.ullberg.us/v1alpha1
# kind: Application
# metadata:
#   name: switch
#   namespace: hajimari
# spec:
#   name: Main switch
#   group: Infrastructure
#   icon: material-symbols:switch
#   url: http://switch.{{ .Values.cluster.top_level_domain }}
#   info: Manage switch
# ---
# apiVersion: startpunkt.ullberg.us/v1alpha1
# kind: Application
# metadata:
#   name: poe-switch
#   namespace: hajimari
# spec:
#   name: PoE switch
#   group: Infrastructure
#   icon: material-symbols:switch
#   url: http://poe-switch.{{ .Values.cluster.top_level_domain }}
#   info: Manage switch
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Application
metadata:
  name: artifactory
  namespace: hajimari
spec:
  name: Artifactory
  group: Infrastructure
  icon: simple-icons:jfrog
  url: http://artifactory.{{ .Values.cluster.top_level_domain }}:8082
  info: File/image repository