apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Application
metadata:
  name: nas
  namespace: startpunkt
spec:
  name: Synology
  group: Infrastructure
  icon: nas
  url: http://nas.{{ .Values.cluster.top_level_domain }}
  info: Storage
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Application
metadata:
  name: valetudo
  namespace: startpunkt
spec:
  name: Vacuum
  group: Home Automation
  icon: robot-vacuum
  url: http://valetudo.{{ .Values.cluster.top_level_domain }}
  info: Home automation
---
apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: startpunkt
spec:
  name: UniFi
  group: Infrastructure
  icon: arcticons:unifi-network
  url: http://unifi.{{ .Values.cluster.top_level_domain }}:8443
  info: Manage WIFI 
# ---
# apiVersion: startpunkt.ullberg.us/v1alpha1
# kind: Application
# metadata:
#   name: firewall
#   namespace: startpunkt
# spec:
#   name: Router
#   group: Infrastructure
#   icon: router-network
#   url: http://firewall.{{ .Values.cluster.top_level_domain }}
#   info: Manage firewall
# ---
# apiVersion: startpunkt.ullberg.us/v1alpha1
# kind: Application
# metadata:
#   name: switch
#   namespace: startpunkt
# spec:
#   name: Main switch
#   group: Infrastructure
#   icon: material-symbols:switch
#   url: http://switch.{{ .Values.cluster.top_level_domain }}
#   info: Manage switch
# ---
# apiVersion: startpunkt.ullberg.us/v1alpha1
# kind: Application
# metadata:
#   name: poe-switch
#   namespace: startpunkt
# spec:
#   name: PoE switch
#   group: Infrastructure
#   icon: material-symbols:switch
#   url: http://poe-switch.{{ .Values.cluster.top_level_domain }}
#   info: Manage switch
