---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 50-master-system-reserved
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - contents:
            source: 'data:,NODE_SIZING_ENABLED%3Dfalse%0ASYSTEM_RESERVED_MEMORY%3D2Gi%0ASYSTEM_RESERVED_CPU%3D1%0ASYSTEM_RESERVED_ES%3D2Gi'
          mode: 420
          overwrite: true
          path: /etc/node-sizing-enabled.env
