---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-app-config
  labels:
    kasten/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- if .Values.cluster.storage.config.storageClass }}
  storageClassName: {{ .Values.cluster.storage.config.storageClass }}
{{- end }}
