apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
  name: db
  namespace: litellm
spec:
  clusterIP: None
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    service: db
