apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-redis-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
data:
  redis.conf: |
    # Redis configuration for LiteLLM
    bind 0.0.0.0
    port 6379

    # Memory management
    maxmemory 256mb
    maxmemory-policy allkeys-lru

    # Persistence
    save 900 1
    save 300 10
    save 60 10000

    # Security - disable dangerous commands
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command DEBUG ""
    rename-command CONFIG ""
    rename-command SHUTDOWN SHUTDOWN_MENOT
    rename-command EVAL ""

    # Logging
    loglevel notice

    # Performance
    tcp-keepalive 60
    timeout 300
