---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  all:
    desc: Run all validation tasks
    summary: |
      Comprehensive validation suite that runs all available validation tasks
      including helm chart validation and linting. This task serves as the
      entry point for all validation workflows.
    cmds:
      - echo "🚀 Running all validation tasks..."
      - task: adr
      - task: :helm:validate-all
      - echo "✅ All validation tasks completed successfully!"

  helm:
    desc: Run helm validation and linting
    summary: |
      Runs helm chart validation and linting tasks.
      Alias for helm:validate-all for convenience.
    cmds:
      - task: :helm:validate-all

  adr:
    desc: Validate ADR (Architecture Decision Record) files
    summary: |
      Validates ADR markdown files under docs/decisions/ for:
        - Filename convention: NNNN-title.md (4-digit index)
        - Presence of key sections: top-level title, Context and Problem Statement, Decision Outcome
        - Optional frontmatter correctness when present (status, date YYYY-MM-DD, decision-makers)
        - Numbering checks (duplicate/malformed numbers error; gaps warning)
      The template.md file is ignored.
    cmds:
      - chmod +x scripts/validate-adr.sh
      - scripts/validate-adr.sh
