---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  all:
    desc: Run all validation tasks (online by default)
    summary: |
      Comprehensive validation suite that runs all available validation tasks
      including helm chart validation, linting, and online icon validation
      against the Iconify database. This task serves as the entry point
      for all validation workflows.
    silent: true
    cmds:
      - echo "🚀 Running all validation tasks (online mode)..."
      - task: adr
      - task: :helm:validate-all
      - echo "✅ All validation tasks completed successfully!"

  all-offline:
    desc: Run all validation tasks (offline mode)
    summary: |
      Comprehensive validation suite that runs all available validation tasks
      including helm chart validation, linting, and offline icon validation
      without making any network requests.
    silent: true
    cmds:
      - echo "🚀 Running all validation tasks (offline mode)..."
      - task: adr
      - task: :helm:validate-all-offline
      - echo "✅ All validation tasks completed successfully!"

  helm:
    desc: Run helm validation and linting
    summary: |
      Runs helm chart validation and linting tasks.
      Alias for helm:validate-all for convenience.
    silent: true
    cmds:
      - task: :helm:validate-all

  adr:
    desc: Validate ADR (Architecture Decision Record) files
    summary: |
      Validates ADR markdown files under docs/decisions/ for:
        - Filename convention: NNNN-title.md (4-digit index)
        - Presence of key sections: top-level title, Context and Problem Statement, Decision Outcome
        - Optional frontmatter correctness when present (status, date YYYY-MM-DD, decision-makers)
        - Numbering checks (duplicate/malformed numbers error; gaps warning)
      The template.md file is ignored.
    silent: true
    sources:
      - docs/decisions/*.md
      - scripts/validate-adr.sh
    generates:
      - .task-cache/adr-validation.txt
    method: checksum
    cmds:
      - chmod +x scripts/validate-adr.sh
      - scripts/validate-adr.sh
      - mkdir -p .task-cache && touch .task-cache/adr-validation.txt
