---
# Areas
- name: area/bootstrap
  color: "0e8a16"
- name: area/docs
  color: "0e8a16"
- name: area/github
  color: "0e8a16"
- name: area/charts
  color: "0e8a16"
- name: area/cluster
  color: "0e8a16"
- name: area/roles
  color: "0e8a16"
- name: area/renovate
  color: "0e8a16"
- name: area/taskfile
  color: "0e8a16"
# Renovate Types
- name: renovate/container
  color: "027fa0"
- name: renovate/github-action
  color: "027fa0"
- name: renovate/grafana-dashboard
  color: "027fa0"
- name: renovate/github-release
  color: "027fa0"
- name: renovate/helm
  color: "027fa0"
# Semantic Types
- name: type/digest
  color: "ffeC19"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"
- name: type/break
  color: "F6412D"
# Release Issue
- name: image-not-found
  color: "ee0701"
# Uncategorized
- name: hold
  color: "ee0701"
- name: bug
  color: "ee0701"
- name: do-not-merge
  color: "ee0701"
- name: docs
  color: "F4D1B7"
- name: enhancement
  color: "84b6eb"
- name: broken-links
  color: "7B55D7"
- name: question
  color: "cc317c"
- name: community
  color: "0e8a16"
