kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    route.openshift.io/termination: "edge"
  name: ultrafeeder
  namespace: adsb
spec:
  path: /
  to:
    kind: Service
    name: adsb-ultrafeeder
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
