---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: adsb-scc
allowedCapabilities:
- NET_BIND_SERVICE
defaultAddCapabilities:
- NET_BIND_SERVICE
requiredDropCapabilities:
- KILL
- MKNOD
- SYS_CHROOT
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{.Release.Namespace}}:adsb-sa