---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: adsb-scc
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{.Release.Namespace}}:adsb-sa