---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]
shopt: [globstar]

includes:
  git: .taskfiles/git
  helm: .taskfiles/helm
  validate: .taskfiles/validate

tasks:
  default: task --list

  clean:
    desc: Clean task cache to force re-running of all cached tasks
    summary: |
      Removes the .task-cache directory which contains checksum files
      used by Task to determine if tasks need to be re-run. Use this
      to force all validation tasks to run again regardless of file changes.
    silent: true
    cmd: rm -rf .task-cache

  new-chart:
    desc: Scaffold a new chart by copying charts/media/sonarr
    summary: |
      Interactively prompts for chart details (name, image repo/tag, description,
      port, icon, group, iconColor, etc.) and creates a new chart under charts/media/.
      Also updates cluster/templates/media.yaml ApplicationSet with the new application.
    silent: true
    cmds:
      - bash scripts/scaffold-new-chart.sh
