---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set: [pipefail]
shopt: [globstar]

includes:
  git: .taskfiles/git
  helm: .taskfiles/helm
  validate: .taskfiles/validate

tasks:
  default: task --list
