{{- if .Capabilities.APIVersions.Has "console.openshift.io/v1" }}
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: "{{ .Release.Name }}-namespace-dashboard-link"
spec:
  href: "https://apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}"
  location: NamespaceDashboard
  namespaceDashboard:
    namespaces:
      - {{ .Release.Namespace }}
  text: "Access Application"
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: "{{ .Release.Name }}-application-menu-link"
spec:
  href: "https://apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}"
  location: ApplicationMenu
  applicationMenu:
    section: {{ .Values.application.group | quote }}
    imageURL: {{ .Values.application.image | quote }}
  text: {{ .Values.application.name | quote }}
{{- end }}
