---
apiVersion: v2
description: A Helm chart to install media applications to the clsuter.
name: media
version: 0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
