storage:
  data:
    storageClassName: synology-iscsi

network:
  mqtt:
    externalIP: 192.168.0.100
    keepalivegroup: lan

app-template:
  controllers:
    main:
      type: statefulset
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        kasten/backup: "true"
        app: mosquitto
        version: 1.0.0
      containers:
        main:
          image:
            # renovate: docker-image
            repository: public.ecr.aws/docker/library/eclipse-mosquitto
            tag: 2.0.20
            pullPolicy: Always
          args:
          - sh
          - -c
          - exec mosquitto -c "/config/mosquitto.conf"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
              spec:
                failureThreshold: 30
                periodSeconds: 5
  service:
    main:
      controller: main
      enabled: false

  serviceAccount:
    name: mosquitto-sa

  persistence:
    config:
      name: mosquitto-config
      type: configMap

    data:
      enabled: true
      existingClaim: mosquitto-data-volume
      globalMounts:
        - path: /data

  defaultPodOptions:
    securityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000