applications:
  bazarr: false
  gaps: false
  kapowarr: true
  kavita: false
  lidarr: false
  metube: false
  overseerr: false
  pinchflat: false
  prowlarr: false
  radarr: false
  readarr: false
  sabnzbd: false
  sonarr: false
  tautulli: false
