apiVersion: v1
kind: Secret
metadata:
  name: litellm-pg-user
  labels:
    app.kubernetes.io/name: litellm
    app.kubernetes.io/component: database
stringData:
  username: litellm
  password: pX7b1Nf3KzQ4wRs9hJ2LmV8d
