{{- if .Values.apiKeysSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apiKeysSecret.name }}
  labels:
    app.kubernetes.io/name: {{ include "litellm.name" . }}
    app.kubernetes.io/component: api-keys
type: Opaque
stringData:
{{- if .Values.apiKeysSecret.keys }}
{{- range $k := .Values.apiKeysSecret.keys }}
  {{ $k }}: placeholder
{{- end }}
{{- else }}
  PLACEHOLDER: ""
{{- end }}
{{- end }}
