{{- if and (not .Values.existingSecret.name) .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm.fullname" . }}-keys
  labels:
    app.kubernetes.io/name: {{ include "litellm.name" . }}
    app.kubernetes.io/component: keys
type: Opaque
stringData:
  {{ .Values.existingSecret.masterKey }}: {{ .Values.secretValues.masterKey | quote }}
  {{ .Values.existingSecret.saltKey }}: {{ .Values.secretValues.saltKey | quote }}
{{- end }}
