---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
{{- if .Values.application.oauthProxy }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ .Release.Name }}"}}'
{{- end }}
