---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: radarr
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        RADARR__AUTH__APIKEY: "{{ .RADARR_API_KEY }}"

  dataFrom:
    - find:
        path: RADARR_API_KEY
