kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Plex_logo_2022.svg"
    forecastle.stakater.com/appName: "Plex"
    forecastle.stakater.com/group: "Media"
    route.openshift.io/termination: "edge"
  name: plex
  namespace: plex
spec:
  host: plex.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  path: /
  to:
    kind: Service
    name: plex
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
