apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: excalidraw
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: excalidraw
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/media-application
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: cluster.top_level_domain
          value: {{ .Values.cluster.top_level_domain }}
        - name: cluster.name
          value: {{ .Values.cluster.name }}
        - name: cluster.admin_email
          value: {{ .Values.cluster.admin_email }}
        - name: cluster.timezone
          value: {{ .Values.cluster.timezone }}

        - name: application.name
          value: excalidraw
        - name: application.group
          value: Utilities
        - name: application.icon
          value: mdi:draw-pen
        - name: application.image
          value: 'https://raw.githubusercontent.com/excalidraw/excalidraw/refs/heads/master/dev-docs/static/img/logo.svg'
        - name: application.description
          value: "Collaborative whiteboard tool that lets you easily sketch diagrams and share them with others"
        - name: app-template.service.main.ports.http.port
          value: '80'

        # renovate custom-docker versioning=loose
        - name: app-template.controllers.main.containers.main.image.repository
          value: ghcr.io/wipash/excalidraw-collab
        - name: app-template.controllers.main.containers.main.image.tag
          value: 0.17.3
        - name: app-template.controllers.main.containers.main.image.pullPolicy
          value: IfNotPresent
        - name: app-template.controllers.main.containers.main.env.TZ
          value: America/New_York
        # - name: app-template.controllers.main.containers.main.env.COLLAB_ADDR
        #   value: excalidraw.localdomain
        - name: app-template.controllers.main.serviceAccount.name
          value: excalidraw-sa

        - name: app-template.defaultPodOptions.labels.app
          value: excalidraw
        - name: app-template.defaultPodOptions.labels.version
          value: 10.18.6

        - name: app-template.defaultPodOptions.securityContext.runAsUser
          value: "0"
        - name: app-template.defaultPodOptions.securityContext.runAsGroup
          value: "0"

  syncPolicy:
{{ if .Values.spec.syncPolicy.automated.enabled }}
    automated: {}
{{ end }}
    syncOptions:
      - CreateNamespace=true
