apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: utilities
spec:
  project: default
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: litellm
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: charts/litellm
    helm:
      releaseName: litellm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
