apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litellm
  labels:
    app.kubernetes.io/part-of: utilities
spec:
  project: default
  source:
    repoURL: https://github.com/rbales79/openshift.git
    targetRevision: main
    path: charts/litellm
    helm:
      values: |
        existingSecret:
          name: llm-keys
          masterKey: LITELLM_MASTER_KEY
          saltKey: LITELLM_SALT_KEY
  destination:
    server: https://kubernetes.default.svc
    namespace: litellm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
