---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: n8n-scc
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:n8n:n8n-sa