apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-gist
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: git
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: {{ .Values.gist_values.chart_path }}
    helm:
      parameters:
        - name: extraArgs
          value: --values={{ .Values.gist_values.values_url }}
  syncPolicy:
{{ if .Values.spec.syncPolicy.automated.enabled }}
    automated: {}
{{ end }}
    syncOptions:
      - CreateNamespace=true
