spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: YOUR_REPO_URL
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true

cluster:
  top_level_domain: example.com
  name: my-cluster
  admin_email: YOUR_EMAIL
  timezone: YOUR_TIMEZONE

network:
  lan:
    defaultGW: 192.168.0.1

democratic-csi:
  driver:
    config:
      httpConnection:
        host: my-nas
        password: my-password
        username: my-username
      iscsi:
        targetPortal: "my-server[:port]"

media:
  nfs:
    server: my-nas
    path: /mnt/nfs