---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.hajimari.io
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  conversion:
    strategy: None
  group: hajimari.io
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - name
                - group
                - url
              properties:
                name:
                  type: string
                group:
                  type: string
                icon:
                  type: string
                iconColor:
                  type: string
                url:
                  type: string
                info:
                  type: string
                targetBlank:
                  type: boolean
                location:
                  type: integer
            status:
              type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bookmarks.hajimari.io
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  conversion:
    strategy: None
  group: hajimari.io
  names:
    kind: Bookmark
    listKind: BookmarkList
    plural: bookmarks
    singular: bookmark
  preserveUnknownFields: false
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - name
                - group
                - url
              properties:
                name:
                  type: string
                group:
                  type: string
                icon:
                  type: string
                url:
                  type: string
                info:
                  type: string
                targetBlank:
                  type: boolean
                location:
                  type: integer
            status:
              type: object
---
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.startpunkt.ullberg.us
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  group: startpunkt.ullberg.us
  names:
    kind: Application
    plural: applications
    singular: application
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              enabled:
                description: Enable the bookmark
                type: boolean
              group:
                description: Group the bookmark belongs to
                type: string
              icon:
                description: "Application icon, e.g. 'mdi:home', 'https://example.com/icon.png'"
                type: string
              iconColor:
                description: "Application icon color, e.g. 'red'"
                type: string
              info:
                description: Description of the bookmark
                type: string
              location:
                description: Sorting order of the bookmark
                type: integer
              name:
                description: Application name
                type: string
              targetBlank:
                description: Open the URL in a new tab
                type: boolean
              url:
                description: Application URL
                type: string
            required:
            - group
            - name
            - url
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bookmarks.startpunkt.ullberg.us
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  group: startpunkt.ullberg.us
  names:
    kind: Bookmark
    plural: bookmarks
    singular: bookmark
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              group:
                description: Group the bookmark belongs to
                type: string
              icon:
                description: "Bookmark icon, e.g. 'mdi:home', 'https://example.com/icon.png'"
                type: string
              info:
                description: Description of the bookmark
                type: string
              location:
                description: Sorting order of the bookmark
                type: integer
              name:
                description: Bookmark name
                type: string
              targetBlank:
                description: Open the URL in a new tab
                type: boolean
              url:
                description: Bookmark URL
                type: string
            required:
            - group
            - name
            - url
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
