apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: roles/base
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: spec.destination.server
          value: {{ .Values.spec.destination.server }}
        - name: spec.destination.server
          value: {{ .Values.spec.destination.server }}
        - name: spec.source.repoURL
          value: {{ .Values.spec.source.repoURL }}
        - name: spec.source.targetRevision
          value: {{ .Values.spec.source.targetRevision }}
        - name: spec.syncPolicy.automated.enabled
          value: '{{ .Values.spec.syncPolicy.automated.enabled }}'

        - name: cluster.top_level_domain
          value: {{ .Values.cluster.top_level_domain }}
        - name: cluster.name
          value: {{ .Values.cluster.name }}
        - name: cluster.admin_email
          value: {{ .Values.cluster.admin_email }}
        - name: cluster.timezone
          value: {{ .Values.cluster.timezone }}

        - name: network.lan.defaultGW
          value: {{ .Values.network.lan.defaultGW }}
