apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-synology
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: roles/storage-synology
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: spec.destination.server
          value: {{ .Values.spec.destination.server }}
        - name: spec.destination.server
          value: {{ .Values.spec.destination.server }}
        - name: spec.source.repoURL
          value: {{ .Values.spec.source.repoURL }}
        - name: spec.source.targetRevision
          value: {{ .Values.spec.source.targetRevision }}
        - name: spec.syncPolicy.automated.enabled
          value: '{{ .Values.spec.syncPolicy.automated.enabled }}'

        - name: cluster.top_level_domain
          value: {{ .Values.cluster.top_level_domain }}
        - name: cluster.name
          value: {{ .Values.cluster.name }}
        - name: cluster.admin_email
          value: {{ .Values.cluster.admin_email }}
        - name: cluster.timezone
          value: {{ .Values.cluster.timezone }}

        {{ $csi := index .Values "democratic-csi" }}
        - name: democratic-csi.driver.config.httpConnection.host
          value: {{ $csi.driver.config.httpConnection.host }}
        - name: democratic-csi.driver.config.httpConnection.password
          value: {{ $csi.driver.config.httpConnection.password }}
        - name: democratic-csi.driver.config.httpConnection.username
          value: {{ $csi.driver.config.httpConnection.username }}
        - name: democratic-csi.driver.config.iscsi.targetPortal
          value: {{ $csi.driver.config.iscsi.targetPortal }}
          
        {{ $nfs := index .Values "nfs-subdir-external-provisioner" }}
        - name: nfs-subdir-external-provisioner.nfs.server
          value: {{ $nfs.nfs.server }}
        - name: nfs-subdir-external-provisioner.nfs.path
          value: {{ $nfs.nfs.path }}