apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-imagemaid
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: imagemaid
spec:
  schedule: "30 6 * * *"  # Run at 06:30 daily
  timeZone: {{ .Values.cluster.timezone }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .Release.Name }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            app.kubernetes.io/component: imagemaid
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ .Release.Name }}
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 568
            runAsUser: 568
            supplementalGroups:
            - 44
            - 109
            - 100
            - 65535
          containers:
          - name: imagemaid
            image: {{ .Values.pods.imagemaid.image.repository }}:{{ .Values.pods.imagemaid.image.tag }}
            imagePullPolicy: IfNotPresent
            env:
            - name: TZ
              value: {{ .Values.cluster.timezone }}
            - name: PLEX_URL
              value: http://{{ .Release.Name }}.{{ .Release.Namespace }}:32400
            - name: PLEX_PATH
              value: /config/Library/Application Support/Plex Media Server
            - name: MODE
              value: report
            - name: PHOTO_TRANSCODER
              value: 'true'
            envFrom:
            - secretRef:
                name: {{ .Release.Name }}
            volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /config/Library/Application Support/Plex Media Server/Cache
              name: cache
          volumes:
          - name: config
            persistentVolumeClaim:
              claimName: {{ .Release.Name }}-config
          - name: cache
            persistentVolumeClaim:
              claimName: {{ .Release.Name }}-cache
