apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    kasten/backup: "true"
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/controller: main
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/controller: main
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      enableServiceLinks: false
      serviceAccountName: {{ .Release.Name }}
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 568
        runAsUser: 568
        supplementalGroups:
        - 44
        - 109
        - 100
        - 65535
      containers:
        - name: main
          env:
          - name: TZ
            value: {{ .Values.cluster.timezone }}
          - name: PLEX_ADVERTISE_URL
            value: https://{{ .Release.Name }}.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}:443
          {{- range $key, $value := .Values.pods.main.env }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
          image: {{ .Values.pods.main.image.repository }}:{{ .Values.pods.main.image.tag }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /config/Library/Application Support/Plex Media Server/Cache
            name: cache
          - mountPath: /config/Library/Application Support/Plex Media Server/Logs
            name: logs
          - mountPath: /data
            name: data
          - mountPath: /transcode
            name: transcode
          - mountPath: /tmp
            name: tmp
          resources:
            requests:
              gpu.intel.com/i915: 1
            limits:
              gpu.intel.com/i915: 1

        - name: imagemaid
          image: {{ .Values.pods.imagemaid.image.repository }}:{{ .Values.pods.imagemaid.image.tag }}
          imagePullPolicy: IfNotPresent
          env:
          - name: TZ
            value: {{ .Values.cluster.timezone }}
          - name: PLEX_URL
            value: https://{{ .Release.Name }}.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
          - name: PLEX_PATH
            value: /config/Library/Application Support/Plex Media Server
          - name: MODE
            value: report
          - name: PHOTO_TRANSCODER
            value: 'true'
          #- name: SCHEDULE
          #  value: '06:30'
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}
          volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /config/Library/Application Support/Plex Media Server/Cache
            name: cache
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-config
        - name: cache
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-cache
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data-volume
        - name: logs
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: transcode
          emptyDir: {}
