spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: YOUR_REPO_URL
    targetRevision: HEAD

roles:
  - ai

config:
  cluster:
    top_level_domain: example.com
    name: cluster
    admin_email: YOUR_EMAIL
    timezone: YOUR_TIMEZONE

  network:
    lan:
      defaultGW: 192.168.0.1

  democratic-csi:
    driver:
      config:
        httpConnection:
          host: my-nas
          password: my-password
          username: my-username
        iscsi:
          targetPortal: "my-server[:port]"

  nfs-subdir-external-provisioner:
    nfs:
      server: my-nfs
      path: /nfs/pvc

  media:
    nfs:
      server: my-nas
      path: /mnt/nfs

  certificates:
    issuer: staging # or production
    aws:
      region: YOUR_REGION
      hosted_zone_id: YOUR_HOSTED_ZONE_ID
      access_key_id: YOUR_ACCESS_KEY_ID
      secret_access_key: YOUR_SECRET_ACCESS_KEY
