apiVersion: startpunkt.ullberg.us/v1alpha1
kind: Application
metadata:
  name: ollama
spec:
  name: Ollama
  group: AI/ML
  icon: ollama
  url: https://ollama.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  info: Manages your local language models.
  targetBlank: true
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: ollama-application-menu-link
spec:
  href: https://ollama.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  location: ApplicationMenu
  applicationMenu:
    section: "AI/ML"
    imageURL: https://upload.wikimedia.org/wikipedia/commons/7/7b/Plex_logo_2022.svg
  text: 'Ollama'
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: ollama-namespace-dashboard-link
spec:
  href: https://ollama.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  location: NamespaceDashboard
  namespaceDashboard:
    namespaces:
      - ollama
  text: 'Access Application'