kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    route.openshift.io/termination: "edge"
  name: ollama
  namespace: ollama
spec:
  host: ollama.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
  path: /
  to:
    kind: Service
    name: ollama
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
