---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: ollama-scc
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
allowPrivilegedContainer: true
allowHostNetwork: true
allowHostPorts: true
allowHostDirVolumePlugin: true
allowPrivilegeEscalation: true
users:
- system:serviceaccount:{{.Release.Namespace}}:ollama-sa