---
apiVersion: v2
description: A Helm chart to create Let's Encrypt configuration in an OpenShift cluster.
name: certificates
version: 0.1.3
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
keywords:
  - certificates
  - Let's Encrypt
  - OpenShift
  - cert-manager