---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://192.168.1.6:8200"
      path: "kv"
      version: "v2"
      auth:
        # Using token-based authentication
        tokenSecretRef:
          name: "vault-token"
          namespace: "cert-manager"
          key: "token"
