---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical-backend
spec:
  provider:
    infisical:
      serverURL: "https://app.infisical.com" # or your self-hosted URL
      auth:
        machineIdentityAuth:
          clientId: "your-machine-identity-client-id"
          clientSecretSecretRef:
            secretName: "infisical-auth"
            secretNamespace: "cert-manager"
            secretKey: "clientSecret"
