---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://192.168.1.6:8200"
      path: "secret"
      version: "v2"
      auth:
        # Using Kubernetes service account authentication
        kubernetes:
          mountPath: "auth/kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "eso-vault"
            namespace: "external-secrets"
