apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: external-secrets-operator
    app.kubernetes.io/component: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-vault-auth
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-vault-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-vault-auth
subjects:
- kind: ServiceAccount
  name: external-secrets-operator
  namespace: cert-manager
