---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: cert-manager
type: Opaque
data:
  # Base64 encoded Vault token
  # Replace with your actual Vault token: echo -n "your-vault-token" | base64
  token: "aHZzLkNBRVNJRU5CMXNGaV9sNnFMdVNkRWFXRW5aanJRRm8ydjFXSUdTQ2hXb3pCOFhDaEdoNEtIR2gyY3k1VmIzZExNbkpoTjFnd2RWSlZXbEIxVURGSFpYRlRXV2c="
