spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: YOUR_REPO_URL
    targetRevision: HEAD

cluster:
  top_level_domain: example.com
  name: my-cluster
  admin_email: YOUR_EMAIL
  timezone: YOUR_TIMEZONE
