apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  labels:
    kasten/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.openwebui.persistence.size }}
{{- if .Values.cluster.storage.config.storageClass }}
  storageClassName: {{ .Values.cluster.storage.config.storageClass }}
{{- end }}
