kind: Service
apiVersion: v1
metadata:
  name: satisfactory
  annotations:
    coredns.io/hostname: satisfactory
    keepalived-operator.redhat-cop.io/keepalivedgroup: "keepalived-operator/{{ .Values.network.satisfactory.keepalivegroup }}"
spec:
  externalIPs:
    - {{ .Values.network.satisfactory.externalIP }}
  ports:
    - port: 7777
      nodePort: 7777
      protocol: UDP
      name: "game"
      targetPort: 7777
    - port: 7777
      nodePort: 7777
      protocol: TCP
      name: "gametcp"
      targetPort: 7777
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: satisfactory
    app.kubernetes.io/name: satisfactory
