{{ $at := index .Values "app-template" }}
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: satisfactory-scc
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{.Release.Namespace}}:{{ $at.controllers.main.serviceAccount.name }}