apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-nfs-subdir-external-provisioner
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nfs-subdir-external-provisioner
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/nfs-subdir-external-provisioner
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: nfs-subdir-external-provisioner.nfs.server
          value: {{ index .Values "nfs-subdir-external-provisioner" "nfs" "server" }}
        - name: nfs-subdir-external-provisioner.nfs.path
          value: {{ index .Values "nfs-subdir-external-provisioner" "nfs" "path" }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true