apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    app.kubernetes.io/part-of: hyperconverged-cluster
    cdi.kubevirt.io: ''
  name: synology-iscsi
spec:
  claimPropertySets:
    - accessModes:
      - ReadWriteOnce
      volumeMode: 
        Filesystem
