---
apiVersion: v2
description: A Helm chart to install Monica.
name: monica
version: 0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: Magnus Ullberg
    email: magnus@ullberg.us
dependencies:
  - name: monica
    version: "0.10.0"
    repository: "oci://ghcr.io/gabe565/charts"
