apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Release.Name }}-acm
spec:
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  goTemplate: true
  generators:
    - list:
        elements:
          # Install in dependency order: MCE first, then cluster-manager, then ACM
          - name: multicluster-engine
          - name: cluster-manager
          - name: advanced-cluster-management
  template:
    metadata:
      name: '{{ "{{" }} .name {{ "}}" }}'
      namespace: "openshift-gitops"
    spec:
      ignoreDifferences:
      - kind: Application
        group: argoproj.io
        jsonPointers:
        - /spec/syncPolicy
      project: default
      destination:
        server: {{ .Values.spec.destination.server }}
        namespace: "openshift-gitops"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      source:
        repoURL: {{ .Values.spec.source.repoURL }}
        path: charts/{{ "{{" }} default "acm" .group {{ "}}" }}/{{ "{{" }} .name {{ "}}" }}
        targetRevision: {{ .Values.spec.source.targetRevision }}
        helm:
          valuesObject:
            spec:
{{ .Values.spec | toYaml | nindent 14 }}
{{ .Values.config | toYaml | nindent 12 }}
