apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |-
    endpoints:
      - name: {{ .Values.application.name | quote }}
        group: productivity
        url: https://{{ .Release.Name }}.apps.{{ .Values.cluster.name }}.{{ .Values.cluster.top_level_domain }}
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[BODY] == pat(*Excalidraw*)"
