{{ if .Values.applications.bazarr }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bazarr
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bazarr
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/media/bazarr
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: cluster.top_level_domain
          value: {{ .Values.cluster.top_level_domain }}
        - name: cluster.name
          value: {{ .Values.cluster.name }}
        - name: cluster.admin_email
          value: {{ .Values.cluster.admin_email }}
        - name: cluster.timezone
          value: {{ .Values.cluster.timezone }}

        - name: storage.media.nfs.server
          value: {{ .Values.media.nfs.server }}
        - name: storage.media.nfs.path
          value: {{ .Values.media.nfs.path }}
  syncPolicy:
{{ if .Values.spec.syncPolicy.automated.enabled }}
    automated: {}
{{ end }}
    syncOptions:
      - CreateNamespace=true
{{ end }}