{{- if .Values.clusterManager.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
---
apiVersion: operator.open-cluster-management.io/v1
kind: ClusterManager
metadata:
  name: {{ .Values.clusterManager.name }}
spec:
  registrationImagePullSpec: quay.io/open-cluster-management/registration
  workImagePullSpec: quay.io/open-cluster-management/work
  placementImagePullSpec: quay.io/open-cluster-management/placement
{{- end }}
