apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-error-code-pages
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: openshift-config
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/custom-error-code-pages
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true