apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery-config
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/node-feature-discovery-config
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
  syncPolicy:
    automated:
      selfHeal: true