apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: startpunkt
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: startpunkt
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/startpunkt
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters:
        - name: cluster.top_level_domain
          value: {{ .Values.cluster.top_level_domain }}
        - name: cluster.name
          value: {{ .Values.cluster.name }}
        - name: cluster.admin_email
          value: {{ .Values.cluster.admin_email }}
        - name: app-template.controllers.main.containers.main.env.TZ
          value: {{ .Values.cluster.timezone }}
        - name: app-template.controllers.main.containers.main.env.LOG_LEVEL
          value: INFO
        - name: startpunkt.ingress.enabled
          value: "false"
        - name: startpunkt.openshift.enabled
          value: "false"
        - name: startpunkt.hajimari.enabled
          value: "false"
        - name: startpunkt.istio.virtualservice.enabled
          value: "false"        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true