{{- if .Capabilities.APIVersions.Has "startpunkt.ullberg.us/v1alpha2" }}
---
apiVersion: startpunkt.ullberg.us/v1alpha2
kind: Bookmark
metadata:
  name: spotify
spec:
  name: Spotify
  group: Entertainment
  icon: simple-icons:spotify
  url: https://browse.spotify.com/
  info: Music Streaming
{{- end }}
