apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bazarr
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bazarr
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/media/bazarr
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valuesObject:
{{- with .Values.config }}
        {{. | toYaml | nindent 8 }}
{{- end }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
