{{ if .Values.applications.sabnzbd }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sabnzbd
    server: "{{ .Values.spec.destination.server }}"
  project: default
  source:
    path: charts/media/sabnzbd
    repoURL: "{{ .Values.spec.source.repoURL }}"
    targetRevision: "{{ .Values.spec.source.targetRevision }}"
    helm:
      valuesObject:
{{- with .Values }}
  {{. | toYaml | nindent 10 }}
{{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}
